<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>up2date on Major Hayden 🤠</title><link>https://major.io/tags/up2date/</link><description>Recent content in up2date on Major Hayden 🤠</description><generator>Hugo -- gohugo.io</generator><copyright>&lt;a href="https://creativecommons.org/licenses/by-sa/2.0/" target="_blank" rel="noopener">CC BY-SA 2.0&lt;/a></copyright><lastBuildDate>Sun, 27 May 2007 16:38:32 +0000</lastBuildDate><atom:link href="https://major.io/tags/up2date/index.xml" rel="self" type="application/rss+xml"/><item><title>rpmdb: Lock table is out of available locker entries</title><link>https://major.io/2007/05/27/rpmdb-lock-table-is-out-of-available-locker-entries/</link><pubDate>Sun, 27 May 2007 16:38:32 +0000</pubDate><guid>https://major.io/2007/05/27/rpmdb-lock-table-is-out-of-available-locker-entries/</guid><description>If up2date throws some horrible Python errors and rpm says “rpmdb: Lock table is out of available locker entries”, you can restore your system to normality with the following:
The errors:
rpmdb: Lock table is out of available locker entries error: db4 error(22) from db-&amp;gt;close: Invalid argument error: cannot open Packages index using db3 - Cannot allocate memory (12) error: cannot open Packages database in /var/lib/rpm Make a backup of /var/lib/rpm in case you break something:</description></item></channel></rss>